export const menuItems = [
  // SOUP
  {
    id: 1,
    name: "Veg Manchow Soup",
    description: "Hot and spicy vegetable soup",
    price: 80,
    category: "Soup",
    popular: false,
  },
  {
    id: 2,
    name: "Hot N Sour Soup",
    description: "Tangy vegetable soup",
    price: 90,
    category: "Soup",
    popular: true,
  },

  // BURGER
  {
    id: 3,
    name: "Veg Burger",
    description: "Classic veggie burger",
    price: 90,
    category: "Burger",
    popular: false,
  },
  {
    id: 4,
    name: "Veg Cheese Burger",
    description: "Veg burger with cheese",
    price: 100,
    category: "Burger",
    popular: true,
  },
  {
    id: 5,
    name: "Paneer Burger",
    description: "Paneer patty burger",
    price: 110,
    category: "Burger",
    popular: true,
  },
  {
    id: 6,
    name: "Paneer Cheese Burger",
    description: "Paneer burger with cheese",
    price: 120,
    category: "Burger",
    popular: true,
  },

  // MOMOS
  {
    id: 7,
    name: "Veg Steam Momos",
    description: "Steamed vegetable momos",
    price: 50,
    category: "Momos",
    popular: false,
  },
  {
    id: 8,
    name: "Veg Fried Momos",
    description: "Crispy fried vegetable momos",
    price: 60,
    category: "Momos",
    popular: true,
  },
  {
    id: 9,
    name: "Paneer Steam Momos",
    description: "Steamed paneer momos",
    price: 80,
    category: "Momos",
    popular: false,
  },
  {
    id: 10,
    name: "Paneer Fried Momos",
    description: "Fried paneer momos",
    price: 90,
    category: "Momos",
    popular: true,
  },
  {
    id: 11,
    name: "Cheese Corn Steam Momos",
    description: "Steamed cheese corn momos",
    price: 90,
    category: "Momos",
    popular: false,
  },
  {
    id: 12,
    name: "Cheese Corn Fried Momos",
    description: "Fried cheese corn momos",
    price: 100,
    category: "Momos",
    popular: true,
  },
  {
    id: 13,
    name: "Kurkure Momos",
    description: "Extra crispy kurkure momos",
    price: 110,
    category: "Momos",
    popular: true,
  },
];